# ĐẠI HỌC QUÓC GIA THÀNH PHÓ HỎ CHÍ MINH TRƯỜNG ĐẠI HỌC BÁCH KHOA 

![[753a4045d3240c9a8f090ccddefd8081_p1_img1.jpeg]]

## BÁO CÁO BÀI TẬP LỚN MÔN XÁC SUÁT THÓNG KÊ (MT2013)

Đề tài 04

XÁC ĐỊNH MỨC ĐỘ ẢNH HƯỚNG CÁC THÔNG SÓ ĐIỀU CHÍNH TRONG MÁY IN 3D ĐẾN CHÁT LƯỢNG IN - ĐỘ CHÍNH XÁC - ĐỘ BÊN

| STT | Họ và tên | MSSV | Lớp | Khoa |
| :-- | :-- | :-- | :-- | :-- |

Giáo viên hướng dẫn: TS. Phan Thị Hường

---

# BẢNG PHÂN CÔNG CÔNG VIỆC

Nhóm trưởng:

|  STT | MSSV | Họ và tên | Nhiệm vụ được
phân công | Cộng / trừ  |
| --- | --- | --- | --- | --- |
|  |   |   |   |   |

---

# MỤC LỤC 

PHẦN 1. TỔNG QUAN DỮ LIỆU ..... 5
PHẢN 2. KIẾN THỨC NÊN ..... 7
2.1. Giới thiệu mô hình hồi quy tuyến tính bội. ..... 7
2.2. Ước lượng các tham số của mô hình hồi quy tuyến tính bội. ..... 7
2.2.1. Hàm hồi quy tổng thể (PRF - Population Regression Function): ..... 7
2.2.2. Hàm hồi quy mẫu (SRF - Sample Regression Function): ..... 8
2.2.3. Phương pháp bình phương nhỏ nhất (Ordinary Least Squares) ..... 8
2.2.4. Độ phù hợp của mô hình Để có thể biết mô hình giải thích được như thế nào hay bao nhiêu \% biến động của biến phụ thuộc, người ta sử dụng R2 ..... 10
2.2.5. Khoảng tin cậy và kiểm định các hệ số hồi quy. ..... 11
2.2.6. Kiểm định ý nghĩa của mô hình ..... 12
PHẢN 3. TIÊN XỬ LÝ SỐ LIỆU ..... 14
3.1. Đọc dữ liệu ..... 14
3.2. Tìm dữ liệu khuyết ..... 15
4.1. Tính thống kê mô tả cho các biến liên tục. ..... 15
4.2. Lập bảng tần số cho các biến phân loại. ..... 16
4.3. Vẽ đồ thị histogram thể hiện phân phối cho biến liên tục tension_strength, roughness, elongation. ..... 16
4.4. Vẽ các đồ thị boxplot thể hiện phân phối của biến liên tục tension_strength, roughness, elongation theo các biến phân loại ..... 17
4.5. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biến tension_strength và các biến liên tục. ..... 19
4.6. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biến elogation và các biến liên tục. ..... 21
4.7. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biến roughness và các biến liên tục. ..... 22
4.8. Vẽ đồ thị ma trận tương quan giữa các biến trong bộ dữ liệu. ..... 23
PHẢN 5. THỐNG KÊ SUY DIÊN ..... 24
5.1. Xây dựng mô hình hồi quy. ..... 24

---

5.2. Thực hiện vẽ đồ thị kiểm tra các giả định: ..... 28
PHÂN 6. THÁO LUẬN VÀ MỞ RỌNG ..... 31
PHÂN 7. NGUÔN DỮ LIỆU VÀ NGUÔN CODE ..... 31
PHÂN 8. TÀI LIỆU THAM KHẢO ..... 32
PHÂN 9. CÁC LỆNH CODE ..... 33
9.1. Tiền xứ lý số liệu. ..... 33
9.2. Thống kê tả. ..... 36
9.3. Thống kê suy diễn. ..... 38

---

# PHÂN 1. TỔNG QUAN DỮ LIỆU 

Tập tin"data.csv" chứa bộ dữ liệu của nhóm nghiên cứu khoa Cơ khí Đại học Selcuk. Mục đích của nghiên cứu là xác định mức độ ảnh hưởng của các thông số điều chỉnh trong máy in 3D đến chất lượng in, độ chính xác và độ giãn của bản in.

Bộ dữ liệu bao gồm 50 quan sát với 9 thông số cài đặt và 3 thông số đầu ra được đo lường.

Dữ liệu gốc được cung cấp tại: https://www.kaggle.com/afumetto/3dprinter

| STT |  | Tên biến | Phân loại | Đơn vị | Giải thích |
| :--: | :--: | :--: | :--: | :--: | :--: |
| 1 | Biến chính | layer_height | Biến <br> liên tục | mm | Độ cao mỗi lớp in |
| 2 |  | nozzle_temperature | Biến <br> liên tục | ${ }^{\circ} \mathrm{C}$ | Nhiệt độ của mũi in |
| 3 |  | bed_temperature | Biến <br> liên tục | ${ }^{\circ} \mathrm{C}$ | Nhiệt độ bản in |
| 4 |  | print_speed | Biến <br> liên tục | $\mathrm{mm} / \mathrm{s}$ | Tốc độ in |
| 5 |  | roughness | Biến <br> liên tục | $\mu \mathrm{m}$ | Độ nhám |
| 6 |  | tension strenght | Biến <br> liên tục | Pa | Sức căng bề mặt (giới hạn bền kéo) |
| 7 |  | elongation | Biến <br> liên tục | mm | Độ giãn dài |
| 8 |  | infill_pattern | Biến <br> phân loại | Gird (Lưới vuông) \& lưới honey_comb | Cấu trúc lưới bên trong chi tiết (mẫu điền đầy) |

---

|  |  |  |  | (tố ong) |  |
| :--: | :--: | :--: | :--: | :--: | :--: |
| 9 |  | material | Biến <br> phân loại | Nhựa PLA \& <br> ABS | Vật liệu |
| 10 | Biến <br> phụ | infill density | Biến <br> liên tục | $\%$ | Mật độ lấp đầy |
| 11 |  | wall_thickness | Biến <br> liên tục | mm | Độ dày tường |
| 12 |  | fan_speed | Biến <br> liên tục | $\mathrm{mm} / \mathrm{s}$ | Tốc độ quạt |

---

# PHÂN 2. KIẾN THỨC NÊN 

## HỎI QUY.

Hồi quy chính là một phương pháp thống kê để thiết lập mối quan hệ giữa một biến phụ thuộc và một nhóm tập hợp các biến độc lập. Mô hình với một biến phụ thuộc với hai hoặc nhiều biến độc lập được gọi là hồi quy bội (hay còn gọi là hồi quy đa biến).

Ví dụ: Chi tiêu của hộ gia đình về thực phẩm phụ thuộc vào quy mô hộ gia đình, thu nhập, vị trí địa lý,...; Tỳ lệ từ vong trẻ em của một quốc gia phụ thuộc vào thu nhập bình quân đầu người, trình độ giáo dục,...; Lương của một người phụ thuộc vào chức vụ, kinh nghiệm, độ tuổi,...

### 2.1. Giới thiệu mô hình hồi quy tuyến tính bội.

Mô hình hồi quy tuyến tính bội có dạng tổng quát như sau:

$$
\mathrm{Y}=\beta 1+\beta 2 \mathrm{X} 2+\beta 3 \mathrm{X} 3+\ldots+\beta \mathrm{kXk}+\mathrm{u}
$$

Trong đó:
Y: biến phụ thuộc
Xi: biến độc lập
ß1: hệ số tự do (hệ số chặn)
ßi: hệ số hồi quy riêng.
ßi đo lường tác động riêng phần của biến Xi lên Y với điều kiện các biến số khác trong mô hình không đổi. Cụ thể hơn, nếu các biến khác trong mô hình không đổi, giá trị kỳ vọng của Y sẽ tăng $\beta i$ đơn vị nếu Xi tăng 1 đơn vị u: sai số ngẫu nhiên.

Như vậy, "Hồi quy tuyến tính" là một phương pháp để dự đoán giá trị biến phụ thuộc $(\mathrm{Y})$ dựa trên giá trị của biến độc lập $(\mathrm{X})$. Thuật ngữ tuyến tính dùng để chỉ rằng bản chất của các thông số của tổng thể $\beta 1$ và $\beta i$ là tuyến tính (bậc nhất). Nó có thể được sử dụng cho các trường hợp chúng ta muốn dự đoán một số lượng liên tục. Ví dụ: dự đoán thời gian người dùng dừng lại một trang nào đó hoặc số người đã truy cập vào một website nào đó v.v... Bằng dữ liệu thu thập được, ta đi ước lượng hàm hồi quy của tổng thể, đó là ước lượng các tham số của tổng thể: $\beta 1, \beta 2, \ldots, \beta \mathrm{k}$.

## 2.2. Ước lượng các tham số của mô hình hồi quy tuyến tính bội.

### 2.2.1. Hàm hồi quy tổng thể (PRF - Population Regression Function):

Với Y là biến phụ thuộc, $\mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk}$ là biến độc lập, Y là ngẫu nhiên và có một phân phối xác suất nào đó. Suy ra: Tồn tại $\mathrm{E}(\mathrm{Y} \mid \mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk})=$ giá trị xác định. Do vậy, $\mathrm{F}(\mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk})=\mathrm{E}(\mathrm{Y} \mid \mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk})$ là hàm hồi quy tổng thể của Y theo X 2 , $\mathrm{X} 3, \ldots, \mathrm{Xk}$.

Với một cá thể i, tồn tại ( $\mathrm{X} 2, \mathrm{i}, \mathrm{X} 3, \mathrm{i}, \ldots, \mathrm{Xk}, \mathrm{i}, \mathrm{Yi})$
Ta có: $\mathrm{Yi} \neq \mathrm{F}(\mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk}) \Rightarrow \mathrm{ui}=\mathrm{Yi}-\mathrm{F}$
Do vậy: $\mathrm{Yi}=\mathrm{E}(\mathrm{Y} \mid \mathrm{X} 2, \mathrm{X} 3, \ldots, \mathrm{Xk})+$ ui 6
Hồi quy tổng thể PRF:

---

$\mathrm{Y}=\mathrm{E}(\mathrm{Y} \mid \mathrm{X})+\mathrm{U}$
$\mathrm{E}(\mathrm{Y} \mid \mathrm{X})=\mathrm{F}$

# 2.2.2. Hàm hồi quy mẫu (SRF - Sample Regression Function): 

Do không biết tổng thể, nên chúng ta không biết giá trị trung bình tổng thể của biến phụ thuộc là đúng ở mức độ nào. Do vậy chúng ta phải dựa vào dữ liệu mẫu để ước lượng.

Trên một mẫu có n cá thể, gọi $\widehat{Y}=\widehat{F}\left(X_{2}, X_{3}, \ldots, X_{k}\right)$ là hồi quy mẫu.
Với một cá thể mẫu $\mathrm{Y}_{\mathrm{i}} \neq \widehat{\mathrm{F}}\left(\mathrm{X}_{2, \mathrm{i}}, \mathrm{X}_{3, \mathrm{i}}, \ldots, \mathrm{X}_{\mathrm{k}, \mathrm{i}}\right)$ sinh ra $\mathrm{e}_{\mathrm{i}}=\mathrm{Y}_{\mathrm{i}}-\widehat{\mathrm{F}}\left(\mathrm{X}_{2}, \mathrm{X}_{3}, \ldots, \mathrm{X}_{\mathrm{k}}\right)$; $\mathrm{e}_{\mathrm{i}}$ gọi là phần dư SRF.

Ta có hàm hồi quy mẫu tổng quát được viết dưới dạng như sau:
$\hat{y}_{i}=\widehat{\beta}_{1}+\widehat{\beta}_{2} x_{2, i}+\widehat{\beta}_{3} x_{3, i}+\ldots+\widehat{\beta}_{k} x_{k, i}$
Phần dư sinh ra: $\mathrm{e}_{\mathrm{i}}=\mathrm{y}_{\mathrm{i}}-\hat{y}_{\mathrm{i}}$
Ký hiệu: $\widehat{\beta}_{m}$ là ước lượng của $\beta_{m}$. Chúng ta trông đợi $\widehat{\beta}_{m}$ là ước lượng không chệch của $\beta_{m}$, hơn nữa phải là một ước lượng hiệu quả.

Ước lượng SRF: chọn một phương pháp nào đó để ước lượng các tham số của F qua việc tìm các tham số của $\widehat{F}$ và lấy giá trị quan sát của các tham số này làm giá trị xấp xỉ cho tham số của $F$.

### 2.2.3. Phương pháp bình phương nhỏ nhất (Ordinary Least Squares)

Phương pháp bình phương nhỏ nhất được đưa ra bởi nhà Toán học Đức Carl
Friedrich Gauss. Tư tưởng của phương pháp này là cực tiểu tổng bình phương của các phần dư. Do đó có thể nói để có được hồi quy thích hợp nhất, chúng ta chọn các ước lượng có tung độ gốc và độ dốc sao cho phần dư là nhỏ.
2.2.3.1. Các giả thiết của phương pháp bình phương nhỏ nhất cho mô hình hồi quy tuyến tính bội

Phương pháp bình phương nhỏ nhất (OLS) là phương pháp rất đáng tin cậy trong việc ước lượng các tham số của mô hình, tuy nhiên mô hình ước lượng phải thỏa mãn 7 giả thiết. Khi thỏa mãn các giả thiết, ước lượng bình phương nhỏ nhất (OLS) là ước lượng tuyến tính không chệch có hiệu quả nhất trong các ước lượng. Vì thế phương pháp OLS đưa ra ước lượng không chệch tuyến tính tốt nhất (BLUE).

Kết quả này được gọi là Định lý Gauss - Markov, theo lý thuyết này ước lượng OLS là BLUE, nghĩa là trong tất cả các tổ hợp tuyến tính không chệch của Y, ước lượng OLS có phương sai bè nhất. Các giả thiết như sau:

## Hàm hồi quy là tuyến tính theo các hệ số.

Điều này có nghĩa là quá trình thực hành hồi quy trên thực tế được miêu tả bởi mối quan hệ dưới dạng:

---

$y=\beta 1+\beta 2 X 2+\beta 3 X 3+\ldots+\beta k X k+u$ hoặc mối quan hệ thực tế có thể được viết lại ví dụ như dưới dạng lấy loga cả hai vế.

# * E(ui) = 0: 

Kỳ vọng của các yếu tố ngẫu nhiên ui bằng 0 . Trung bình tổng thể sai số là bằng 0 . Điều này có nghĩa là có một số giá trị sai số mang dấu dương và một số sai số mang dấu âm. Do hàm xem như là đường trung bình nên có thể giả định rằng các sai số ngẫu nhiên trên sẽ bị loại trừ nhau, ở mức trung bình, trong tổng thể.

## * $\operatorname{Var}(\mathbf{u i})=\sigma 2$ :

Phương sai bằng nhau và thuần nhất với mọi ui. Tất cả giá trị u được phân phối giống nhau với cùng phương sai $\sigma 2$, sao cho: $\operatorname{Var}(\mathrm{ui})=\mathrm{E}(\mathrm{ui} 2)=\sigma 2$.

## * ui phân phối chuẩn.

Điều này rất quan trọng khi phát sinh khoảng tin cậy và thực hiện kiểm định giả thuyết trong những phạm vi mẫu là nhỏ. Nhưng phạm vi mẫu lớn hơn, điều này trở nên không mấy quan trọng.

## * Giữa các ui thì độc lập với nhau.

### 2.2.3.2 Uớc lượng.

Ta đặt: yi ký hiệu giá trị thực của biến y tại quan sát i
ỷu ký hiệu giá trị của hàm hồi quy mẫu
ei ký hiệu phần dư yi - ỷi
![[753a4045d3240c9a8f090ccddefd8081_p9_img2.jpeg]]

Hình 1. Đồ thị đường hàm quy tuyến tính.
Do đó cực tiểu hóa $\Sigma\left(y_{i}-\hat{y}_{i}\right)^{2}$ sẽ tương đương với cực tiểu $\Sigma e_{i}{ }^{2}$ từ đó tìm ra $\beta_{0}, \beta_{1}, \ldots$, $\beta_{\mathrm{k}}$

Ta có:

$$
\Sigma \mathrm{e}_{\mathrm{i}}{ }^{2}=\Sigma\left(\mathrm{y}_{\mathrm{i}}-\left(\beta_{1}+\beta_{2} \mathrm{x}_{2, \mathrm{i}}+\beta_{3} \mathrm{x}_{3, \mathrm{i}}+\beta_{4} \mathrm{x}_{4, \mathrm{i}}+\ldots+\beta_{\mathrm{k}} \mathrm{x}_{\mathrm{k}, \mathrm{i}}\right)\right)^{2}
$$

Chúng ta có thiết lập các điều kiện bậc nhất cho phép tính tối thiểu này như sau:

---

$$
\begin{gathered}
\frac{\partial \Sigma e_{i}^{2}}{\partial \beta_{1}}=-2 \Sigma\left(y_{i}-\left(\beta_{1}+\beta_{2} x_{2 i}+\beta_{3} x_{3 i}+\ldots+\beta_{k} x_{k i}\right)\right) x_{i}=0 \\
\frac{\partial \Sigma e_{i}^{2}}{\partial \beta_{2}}=-2 \Sigma\left(y_{i}-\left(\beta_{1}+\beta_{2} x_{2 i}+\beta_{3} x_{3 i}+\ldots+\beta_{k} x_{k i}\right)\right) x_{2 i}=0 \\
\ldots \\
\frac{\partial \Sigma e_{i}^{2}}{\partial \beta_{k}}=-2 \Sigma\left(y_{i}-\left(\beta_{1}+\beta_{2} x_{2 i}+\beta_{3} x_{3 i}+\ldots+\beta_{k} x_{k i}\right)\right) x_{k i}=0
\end{gathered}
$$

Hệ phương trình mà chúng ta có được gọi là hệ phương trình chuẩn của hồi quy mẫu. Chúng ta có thể giải k phương trình chuẩn này để tìm k hệ số $\beta$ chưa biết. $\beta_{1}$, $\beta_{2}, \ldots, \beta_{\mathrm{k}}$ được gọi là các ước lượng bình phương nhỏ nhất.

# 2.2.4. Độ phù hợp của mô hình Để có thể biết mô hình giải thích được như thế nào hay bao nhiêu \% biến động của biến phụ thuộc, người ta sử dụng R2 

Để có thể biết mô hình giải thích được như thế nào hay bao nhiêu \% biến động của biến phụ thuộc, người ta sử dụng $\mathrm{R}^{2}$
Ta có: $\Sigma\left(y_{i}-\bar{y}\right)^{2}=\Sigma\left[\left(y_{i}-\hat{y}_{i}\right)+\left(\hat{y}_{i}-\bar{y}\right)\right]^{2}=\Sigma\left[e_{i}+\left(\hat{y}_{i}-\bar{y}\right)\right]^{2}$

$$
=\Sigma e_{i}^{2}+2 \Sigma e_{i}\left(\hat{y}_{i}-\bar{y}\right)+\Sigma\left(\hat{y}_{i}-\bar{y}\right)^{2}
$$

Đặt:

- $\sum_{i=1}^{n}\left(y_{i}-\bar{y}\right)^{2}:$ SST - Total Sum of Squares
- $\sum_{i=1}^{n}\left(\hat{y}_{i}-\bar{y}\right)^{2}:$ SSR - Regression Sum of Squares
- $\sum_{i=1}^{n}\left(y_{i}-\hat{y}_{i}\right)^{2}:$ SSE - Error Sum of Squares
Do $\sum_{i=1}^{n}\left(y_{i}-\bar{y}\right)^{2}=\sum_{i=1}^{n}\left(\hat{y}_{i}-\bar{y}\right)^{2}+\sum_{i=1}^{n}\left(y_{i}-\hat{y}_{i}\right)^{2}$
Ta có thể viết: SST $=$ SSR + SSE
Ý nghĩa của các thành phần:
$>$ SST là tổng bình phương toàn phần, đo sự biến thiên của các giá trị $y_{i}$ xung quanh giá trị trung tâm của dữ liệu ý.
$>$ SSR là tổng bình phương hồi quy, giải thích sự biến thiên liên quan đến mối quan hệ tuyến tính của X và Y .
$>$ SSE là Tổng bình phương sai số, giải thích sự biến thiên của các yếu tố khác (không liên quan đến mối quan hệ tuyến tính của X và Y .

SST được chia thành 2 phần: một phần do SSR và một phần do SSE gây ra.
Từ $\mathrm{SST}=\mathrm{SSR}+\mathrm{SSE}$, ta chia cả hai về cho SST, ta có:

$$
1=\frac{\mathrm{SSR}}{\mathrm{SST}}+\frac{\mathrm{SSE}}{\mathrm{SST}}=\frac{\Sigma\left(\hat{y}_{i}-\bar{y}\right)^{2}}{\Sigma\left(y_{i}-\bar{y}\right)^{2}}+\frac{\Sigma e_{i}^{2}}{\Sigma\left(y_{i}-\bar{y}\right)^{2}}
$$

---

$$
\mathrm{R}^{2}=\frac{\mathrm{SSR}}{\mathrm{SST}}=1-\frac{\mathrm{SSE}}{\mathrm{SST}}=\frac{\left(\Sigma\left(y_{i}-\bar{y}\right)\left(y_{i}-\bar{y}\right)\right)^{2}}{\left(\Sigma\left(y_{i}-\bar{y}\right)^{2}\right)\left(\Sigma\left(y_{i}-\bar{y}\right)^{2}\right)}
$$

Tỷ số giữa tổng biến thiên được giải thích bởi mô hình cho tổng bình phương cần được giải thích được gọi là hệ số xác định, hay là trị thống kê "good of fit". Từ định nghĩa $\mathrm{R}^{2}$ chúng ta thấy $\mathrm{R}^{2}$ đo tỷ lệ hay số $\%$ của toàn bộ sai lệch Y với giá trị trung bình được giải thích bằng mô hình. Khi đó người ta sử dụng $\mathrm{R}^{2}$ để đo sự phù hợp của hàm hồi quy:

$$
0 \leq \mathrm{R}^{2} \leq 1
$$

$\mathrm{R}^{2}$ cao nghĩa là mô hình ước lượng được giải thích được một mức độ cao biến động của biến phụ thuộc.
$>$ Nếu $\mathrm{R}^{2}=1$, nghĩa là đường hồi quy giải thích $100 \%$ thay đổi của y .
$>$ Nếu $\mathrm{R}^{2}=0$, nghĩa là mô hình không đưa ra thông tin nào về sự thay đổi của biến phụ thuộc y .

Trong mô hình hồi quy đa biến tỷ lệ của toàn bộ sự khác biệt của biến y do tất cả các biến $\mathrm{x}_{2}$ và $\mathrm{x}_{3}$ gây ra được gọi là hệ số xác định bội, ký hiệu là $\mathrm{R}^{2}$

$$
R^{2}=\frac{\beta_{1} \Sigma\left(y_{i}-\bar{y}\right)\left(x_{2 i}-\bar{x}_{2}\right)+\beta_{1} \Sigma\left(y_{i}-\bar{y}\right)\left(x_{3 i}-\bar{x}_{3}\right)}{\Sigma\left(y_{i}-\bar{y}\right)^{2}}=1-\frac{\Sigma e_{i}^{2}}{\Sigma\left(y_{i}-\bar{y}\right)^{2}}
$$

# 2.2.5. Khoảng tin cậy và kiểm định các hệ số hồi quy 

2.2.5.1. Ước lượng khoảng tin cậy đối với các hệ số hồi quy

Mục đích của phân tích hồi quy không phải chỉ suy đoán về $\beta_{1}, \beta_{2}, \ldots, \beta_{\mathrm{k}}$ mà còn phải kiểm tra bản chất sự phụ thuộc. Do vậy cần phải biết phân bố xác suất của $\beta_{1}, \beta_{2}, \ldots, \beta_{\mathrm{k}}$. Các phân bố này phụ thuộc vào phân bố của các $u_{i}$.

Với các giả thiết OLS, $u_{i}$ có phân phối $\mathrm{N}\left(0, \sigma^{2}\right)$. Các hệ số ước lượng tuân theo phân phối chuẩn:
$\left.\bar{\beta}_{j} \sim \mathrm{~N}\left(\beta_{j}, \operatorname{Se}\left(\bar{\beta}_{j}\right)\right)\right.$

$$
\frac{\bar{\beta}_{j}-\beta_{j}}{\operatorname{Se}\left(\bar{\beta}_{j}\right)} \sim \mathrm{T}(\mathrm{n}-\mathrm{k})
$$

Ước lượng phương sai sai số dựa vào các phần dư bình phương tối thiểu. Trong đó k là số hệ số có trong phương trình hồi quy đa biến:

$$
\bar{\sigma}^{2}=\frac{\Sigma \mathrm{e}_{\mathrm{i}}^{2}}{\mathrm{n}-\mathrm{k}}
$$

$>$ Ước lượng 2 phía, ta tìm được $\mathrm{t}_{\frac{\alpha}{2}}(\mathrm{n}-3)=1-\alpha$ thỏa mãn:

---

$$
P\left(-\frac{t_{2}}{2}(n-3)\right) \leq \frac{\beta_{j}-\beta_{j}}{\operatorname{Se}\left(\beta_{j}\right)} \leq P\left(\frac{t_{2}}{2}(n-3)\right)
$$

$>$ Khoảng tin cậy $1-\alpha$ của $\beta_{j}$ là:

$$
\left[\beta_{j}-\frac{t_{2}}{2}(n-3) \operatorname{Se}\left(\beta_{j}\right)\right] ;\left[\beta_{j}+\frac{t_{2}}{2}(n-3) \operatorname{Se}\left(\beta_{j}\right)\right]
$$

# 2.2.5.2 Kiểm định giả thiết đối với $\beta j$ 

Kiểm định ý nghĩa thống kê của các hệ số hồi quy có ý nghĩa hay không: kiểm định rằng biến giải thích có thực sự ảnh hưởng đến biến phụ thuộc hay không. Nói cách khác là hệ số hồi quy có ý nghĩa thống kê hay không.

Có thể đưa ra giả thiết nào đó đối với $\beta_{j}$, chẳng hạn $\beta_{j}=\beta_{j}{ }^{*}$. Nếu giả thiết này đúng thì:

$$
\mathrm{T}=\frac{\beta_{j}-\beta_{j}}{\operatorname{Se}\left(\beta_{j}\right)} \sim \mathrm{T}(\mathrm{n}-\mathrm{k})
$$

Ta có bảng sau:

| Loại giả thiết | Giả thiết $\mathrm{H}_{0}$ | Giả thiết đối $\mathrm{H}_{1}$ | Miễn bác bỏ |
| :--: | :--: | :--: | :--: |
| Hai phía | $\beta_{j}=\beta_{j}{ }^{*}$ | $\beta_{j} \neq \beta_{j}{ }^{*}$ | $\left\|>\mathrm{t}_{\alpha>}>\mathrm{t}_{\mathrm{n}}-\mathrm{k}\right.$ ) |
| Phía phải | $\beta_{j} \leq \beta_{j}{ }^{*}$ | $\beta_{j}>\beta_{j}{ }^{*}$ | $\mathrm{t}>\mathrm{t}_{\alpha}(\mathrm{n}-\mathrm{k})$ |
| Phía trái | $\beta_{j} \geq \beta_{j}{ }^{*}$ | $\beta_{j}<\beta_{j}{ }^{*}$ | $\mathrm{t}<-\mathrm{t}_{\alpha}(\mathrm{n}-\mathrm{k})$ |

Hình 2. Bảng phân loại giả thuyết và kiểm định các hệ số hồi quy.
Kiểm định $\beta_{j}$ :
$\diamond \mathrm{H}_{0}: \beta_{\mathrm{j}}=0 \Leftrightarrow \mathrm{x}_{\mathrm{j}}$ không tác động
$\diamond \mathrm{H}_{1}: \beta_{\mathrm{j}} \neq 0 \Leftrightarrow \mathrm{x}_{\mathrm{j}}$ có tác động
$\beta_{\mathrm{j}}<0 \Leftrightarrow \mathrm{x}_{\mathrm{j}}$ có tác động ngược
$\beta_{\mathrm{j}}>0 \Leftrightarrow \mathrm{x}_{\mathrm{j}}$ có tác động thuận

### 2.2.6. Kiểm định ý nghĩa của mô hình

Trong mô hình hồi quy đa biến, giả thuyết "không" cho rằng mô hình không có ý nghĩa được hiểu là tất cả các hệ số hồi quy riêng đều bằng 0 .

Ứng dụng kiểm định Wald (thường được gọi là kiểm định F) được tiến hành cụ thể như sau:

* Bước 1: Giả thuyết "không" là $\mathrm{H}_{0}: \beta_{2}=\beta_{3}=\ldots=\beta_{\mathrm{k}}=0$.

Giả thuyết đối là $\mathrm{H}_{1}$ : "có ít nhất một trong những giá trị $\beta$ khác không".

---

* Buớc 2: Trước tiên hồi quy Y theo một số hạng không đổi và $\mathrm{X}_{2}, \mathrm{X}_{3}, \ldots, \mathrm{X}_{\mathrm{k}}$, sau đó tính tổng bình phương sai số $\mathrm{RSS}_{\mathrm{U}}, \mathrm{RSS}_{\mathrm{R}}$. Phân phối F là tỷ số của hai biến ngẫu nhiên phân phối khi bình phương độc lập. Điều này cho ta trị thống kê:

$$
\mathrm{F}_{\mathrm{c}}=\frac{\left[\mathrm{RSS}_{\mathrm{R}}-\mathrm{RSS}_{\mathrm{U}}\right] /(\mathrm{k}-\mathrm{m})}{\mathrm{RSS}_{\mathrm{U}} /(\mathrm{n}-\mathrm{k})} \sim \mathrm{F}(\alpha, \mathrm{k}-\mathrm{m}, \mathrm{n}-\mathrm{k})
$$

Vì $\mathrm{H}_{0}: \beta_{2}=\beta_{3}=\ldots=\beta_{\mathrm{k}}=0$, nhận thấy rằng trị thống kê kiểm định đối với giả thuyết này sẽ là:

$$
\mathrm{F}_{\mathrm{c}}=\frac{\mathrm{ESS} /(\mathrm{k}-1)}{\mathrm{RSS} /(\mathrm{n}-\mathrm{k})} \sim \mathrm{F}(\alpha, \mathrm{k}-1, \mathrm{n}-\mathrm{k})
$$

* Buớc 3: Tra số liệu trong bảng F tương ứng với bậc tự do $(\mathrm{k}-1)$ cho tử số và ( n $-\mathrm{k})$ cho mẫu số, và với mức ý nghĩa $\alpha$ cho trước.
* Buớc 4: Bác bỏ giả thuyết $\mathrm{H}_{0}$ ở mức ý nghĩa $\alpha$ nếu $\mathrm{F}_{\mathrm{c}}>\mathrm{F}(\alpha, \mathrm{k}-1, \mathrm{n}-\mathrm{k})$. Đối với phương pháp giá trị p , tính giá trị $\mathrm{p}=\mathrm{P}\left(\mathrm{F}>\mathrm{F}_{\mathrm{c}} \mid \mathrm{H}_{0}\right)$ và bác bỏ giả thuyết $\mathrm{H}_{0}$ nếu $\mathrm{p}<\alpha$.

---

# PHÂN 3. TIÊN XỬ LÝ SÓ LIỆU 

### 3.1. Đọc dữ liệu

Ta dùng hàm read.csv để đọc dữ liệu vào R và hàm head(dữ liệu,10) để xem 10 dòng đầu tiên của dữ liệu:

|  |  | layer_height wall_thickness | infill_density | infill_pattern | nozzle_temper |  |
| :--: | :--: | :--: | :--: | :--: | :--: | :--: |
|  | 1 | 0.02 | 8 | 90 | grid | 220 |
|  | 2 | 0.02 | 7 | 90 | honeycomb | 225 |
|  | 3 | 0.02 | 1 | 80 | grid | 230 |
|  | 4 | 0.02 | 4 | 70 | honeycomb | 240 |
|  | 5 | 0.02 | 6 | 90 | grid | 250 |
|  | 6 | 0.02 | 10 | 40 | honeycomb | 200 |
|  | 7 | 0.02 | 5 | 10 | grid | 205 |
|  | 8 | 0.02 | 10 | 10 | honeycomb | 210 |
|  | 9 | 0.02 | 9 | 70 | grid | 215 |
|  | 10 | 0.02 | 8 | 40 | honeycomb | 220 |
|  | bed_temper | rature | rint_speed | material | fan_speed | roughness |
|  | 1 | 60 | 40 | abs | 0 | 25 |
|  | 2 | 65 | 40 | abs | 25 | 32 |
|  | 3 | 70 | 40 | abs | 50 | 40 |
|  | 4 | 75 | 40 | abs | 75 | 68 |
|  | 5 | 80 | 40 | abs | 100 | 92 |
|  | 6 | 60 | 40 | pla | 0 | 60 |
|  | 7 | 65 | 40 | pla | 25 | 55 |
|  | 8 | 70 | 40 | pla | 50 | 21 |
|  | 9 | 75 | 40 | pla | 75 | 24 |
|  | 10 | 80 | 40 | pla | 100 | 30 |
|  | elongation |  |  |  |  |  |
|  | 1 | 1.2 |  |  |  |  |
|  | 2 | 1.4 |  |  |  |  |
|  | 3 | 0.8 |  |  |  |  |
|  | 4 | 0.5 |  |  |  |  |
|  | 5 | 0.7 |  |  |  |  |
|  | 6 | 1.1 |  |  |  |  |
|  | 7 | 1.3 |  |  |  |  |
|  | 8 | 1.5 |  |  |  |  |
|  | 9 | 1.4 |  |  |  |  |
|  | 10 | 1.7 |  |  |  |  |

Hình 3. Kết quả xem 10 dòng đầu tiên của dữ liệu.
Tạo một tệp con new_DF bao gồm các biến chính cần phân tích:
Ta dùng hàm new_DF <- threedprint_data[,c(các biến chính)] và head(new_DF,15) để xem dữ liệu 15 dòng đầu.

---

![[753a4045d3240c9a8f090ccddefd8081_p15_img3.jpeg]]

Hình 4. Kết quả xem 15 dòng đầu tiên của tệp con mới tạo.

# 3.2. Tìm dữ liệu khuyết 

Ta dùng hàm colSums(is.na(new_DF)) để kiểm tra dữ liệu khuyết trong tệp tin:

| layer_height | wall_thickness | infill_density | infill_pattern nozzle_temperature |  |
| :--: | :--: | :--: | :--: | :--: |
| 0 | 0 | 0 | 0 | 0 |
| bed_temperature | print_speed | material | fan_speed | tension_strenght |
| 0 | 0 | 0 | 0 | 0 |

Hình 5. Kết quả kiểm tra không có dữ liệu khuyết.
Nhận xét: Tệp tin không chứa dữ liệu khuyết.

## PHẦN 4. THÔNG KẾ TẢ

### 4.1. Tính thống kê mô tả cho các biến liên tục.

Tạo function và lập bảng tính thống kê mô tả cho các biến liên tục:

---

|  | layer_height wall_thickness |  |  |  |  |  |
| :--: | :--: | :--: | :--: | :--: | :--: | :--: |
| n | 50.00000000 | 50.000000 | 50.00000 | 50.00000 | 50.000000 | 50.0000 |
| xtb | 0.10600000 | 5.220000 | 53.40000 | 221.50000 | 70.000000 | 64.0000 |
| sd | 0.06439673 | 2.922747 | 25.36348 | 14.82035 | 7.142857 | 29.6923 |
| Q1. $25 \%$ | 0.06000000 | 3.000000 | 40.00000 | 210.00000 | 65.000000 | 40.0000 |
| Q2 | 0.10000000 | 5.000000 | 50.00000 | 220.00000 | 70.000000 | 60.0000 |
| Q3. $75 \%$ | 0.15000000 | 7.000000 | 80.00000 | 230.00000 | 75.000000 | 60.0000 |
| min | 0.02000000 | 1.000000 | 10.00000 | 200.00000 | 60.000000 | 40.0000 |
| max | 0.20000000 | 10.000000 | 90.00000 | 250.00000 | 80.000000 | 120.0000 |
|  | fan_speed |  |  |  |  |  |
| n | 50.00000 | 50.000000 |  |  |  |  |
| xtb | 50.00000 | 20.080000 |  |  |  |  |
| sd | 35.71429 | 8.925634 |  |  |  |  |
| Q1. $25 \%$ | 25.00000 | 12.000000 |  |  |  |  |
| Q2 | 50.00000 | 19.000000 |  |  |  |  |
| Q3. $75 \%$ | 75.00000 | 27.000000 |  |  |  |  |
| min | 0.00000 | 4.000000 |  |  |  |  |
| max | 100.00000 | 37.000000 |  |  |  |  |

Hình 6. Kết quả bảng tính thống kê cho các biến liên tục.
Dựa vào kết quả của biến layer_height ta thấy được:
$\diamond$ n: Độ dài dữ liệu là 50 .
$\diamond \mathrm{xtb}$ : Giá trị x trung bình là 0.106 .
$\diamond \mathrm{sd}$ : Sai số chuẩn là 0.6439673 .
$\diamond \mathrm{Q}_{1}$ : Giá trị của đường phân vị 1 ở mức $25 \%$ là 0.06 .
$\diamond \mathrm{Q}_{2}$ : Giá trị của đường trung vị là 0.10 .
$\diamond \mathrm{Q}_{3}$ : Giá trị của đường phân vị 3 ở mức $75 \%$ là 0.15 .
$\diamond \min$ : Giá trị nhỏ nhất là 0.02 .
$\diamond$ max: Giá trị lớn nhất là 0.20 .

# 4.2. Lập bảng tần số cho các biến phân loại. 

Ta dùng hàm table(dữ liệu\$biến phân loại) để xem kết quả phân loại cho biến infill_pattern.

| grid honeycomb |
| :--: |
| 25 |

Hình 7. Kết quả phân loại cho biến infill_pattern.
Ta dùng hàm table(dữ liệu\$biến phân loại) để xem kết quả phân loại cho biến material.

| abs pla |
| :-- |
| 25 |

Hình 8. Kết quả phân loại cho biến material.
4.3. Vẽ đồ thị histogram thể hiện phân phối cho biến liên tục tension_strength, roughness, elongation.

Ta dùng hàm hist( ) để vẽ đồ thị:

---

![[753a4045d3240c9a8f090ccddefd8081_p17_img4.jpeg]]

Histogram of elongation
![[753a4045d3240c9a8f090ccddefd8081_p17_img5.jpeg]]

Hình 9. Đồ thị cho 3 biến tension_strength, roughness và elongation.

# Nhận xét: 

Đồ thị của biến tension_strength có xu hướng phân phối nghiêng về phía bên trái (lệch trái) và khoảng giá trị phân bố chủ yếu từ 10 đến 30 .

Đồ thị của biến roughness có xu hướng phân phối nghiêng về phía bên trái (lệch trái) và khoảng giá trị phân bố chủ yếu từ 0 đến 300 .

Đồ thị của biến elongation có xu hướng phân phối nghiêng về phía bên trái (lệch trái) và khoảng giá trị phân bố chủ yếu từ 0.5 đến 2.5 .
4.4. Vẽ các đồ thị boxplot thể hiện phân phối của biến liên tục tension_strength, roughness, elongation theo các biến phân loại
$\checkmark$ Biến tension_strength theo các biến phân loại.
Ta dùng hàm boxplot( $\_$) để vẽ đồ thị:

---

![[753a4045d3240c9a8f090ccddefd8081_p18_img6.jpeg]]

Nhận xét:
Không có sự khác biệt nhiều về phân phối của tension_strenght ở 2 nhóm infill_pattern, ta dự đoán yếu tố infill_pattern không ảnh hưởng đến tension_strength.

Có sự khác biệt về phân phối tension_strenght ở 2 nhóm material (chênh lệch giá trị giữa hai hộp), ta dự đoán yếu tố material có ảnh hưởng đến tension_strength.
$\Rightarrow$ Biến roughness theo các biến phân loại.
Ta dùng hàm boxplot( $\_$) để vẽ đồ thị:
![[753a4045d3240c9a8f090ccddefd8081_p18_img7.jpeg]]

Hình 11. Đồ thị cho 2 biến infill_pattern và material.

# Nhận xét: 

Không có sự khác biệt nhiều về phân phối của roughness ở 2 nhóm infill_pattern, ta dự đoán yếu tố infill_pattern không ảnh hưởng đến roughness.

Có sự khác biệt về phân phối roughness ở 2 nhóm material (chênh lệch giá trị giữa hai hộp), ta dự đoán yếu tố material có ảnh hưởng đến roughness.

---

* Biến elongation theo các biến phân loại.

Ta dùng hàm boxplot( $\_$) để vẽ đồ thị:
![[753a4045d3240c9a8f090ccddefd8081_p19_img8.jpeg]]

Nhận xét:
Không có sự khác biệt về phân phối của elongation ở 2 nhóm infill_pattern, ta dự đoán yếu tố infill_pattern không ảnh hưởng đến elongation.

Có sự khác biệt về phân phối elongation ở 2 nhóm material (chênh lệch giá trị giữa hai hộp), ta dự đoán yếu tố material có ảnh hưởng đến elongation.
4.5. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biến tension_strength và các biến liên tục.

Ta dùng hàm plot( $\_$) để vẽ đồ thị:
![[753a4045d3240c9a8f090ccddefd8081_p19_img9.jpeg]]

GVHD: TS. Phan Thị Huờng

---

![[753a4045d3240c9a8f090ccddefd8081_p20_img10.jpeg]]
nozzle_temperature
![[753a4045d3240c9a8f090ccddefd8081_p20_img11.jpeg]]
print_speed
![[753a4045d3240c9a8f090ccddefd8081_p20_img12.jpeg]]
infill_density
![[753a4045d3240c9a8f090ccddefd8081_p20_img13.jpeg]]
bed_temperature
![[753a4045d3240c9a8f090ccddefd8081_p20_img14.jpeg]]
fan_speed

Hình 13. Đồ thị cho 7 biến layer_height, wall_thickness, nozzle_temperature, bed_temperature, print_speed, fan_speed, infill_density.

Nhận xét: Ta nhận thấy các biến đều còn lại có quan hệ tuyển tính rất yếu với biến tension_strength.

---

4.6. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biến elogation và các biến liên tục.

Ta dùng hàm plot( ) để vẽ đồ thị:
![[753a4045d3240c9a8f090ccddefd8081_p21_img15.jpeg]]

---

![[753a4045d3240c9a8f090ccddefd8081_p22_img16.jpeg]]

Hình 14. Đồ thị cho 7 biển layer_height, wall_thickness, infill_density, nozzle_temperature, bed_temperature, fan_speed, print_speed.

Nhận xét: Ta nhận thấy các biển đều còn lại có quan hệ tuyến tính rất yếu với biển elogation.
print_speed
4.7. Vẽ đồ thị phân tán thể hiện mối quan hệ tuyến tính giữa biển roughness và các biển liên tục.

Ta dùng hàm plot( $\_$) để vẽ đồ thị:
![[753a4045d3240c9a8f090ccddefd8081_p22_img17.jpeg]]
![[753a4045d3240c9a8f090ccddefd8081_p22_img18.jpeg]]
![[753a4045d3240c9a8f090ccddefd8081_p22_img19.jpeg]]
fan_speed
![[753a4045d3240c9a8f090ccddefd8081_p22_img20.jpeg]]

---

![[753a4045d3240c9a8f090ccddefd8081_p23_img21.jpeg]]
layer_height
4.8. Vẽ đồ thị ma trận tương quan giữa các biến trong bộ dữ liệu.

Ta dùng hàm corrplot( $\_$) để vẽ đồ thị:

---

![[753a4045d3240c9a8f090ccddefd8081_p24_img22.jpeg]]

Hình 16. Đồ thị ma trận tương quan giữa các biến.
Nhận xét: Từ ma trận tương quan và đồ thị cho thấy:
Hệ số tương quan giữa biến bed_temperater và fan_speed $=1$ nên cho thấy có hiện tượng đa cộng tuyến xảy ra ( 2 biến độc lập này có mối quan hệ phụ thuộc) do đó ta sẽ loại bỏ 1 trong 2 biến này khi xây dựng dựng mô hình. Ở bài toán này ta chọn bỏ biến fan_speed. Từ phần này trở về sau khi ta xây dựng mô hình, ta sẽ không đưa biến fan_speed vào mô hình.

Hệ số tương quan giữa tension_strenght và các biến độc lập cho ta dự đoán tension_strength không có quan hệ tuyến tính mạnh với các biến này.

# PHÂN 5. THÔNG KẾ SUY DIẾN 

Bài toán: Xét sự ảnh hưởng của các biến ở thông số đầu ảnh hưởng đến biến đầu ra tension_strength (sức căng bề mặt in) của máy in 3D như thế nào?

### 5.1. Xây dựng mô hình hồi quy.

Biến phụ thuộc: tension_strength.
Biến dự báo (biến độc lập): layer_height, wall_thickness, infill_density, infill_pattern, nozzle_temperature, bed_temperature, print_speed, material.
$\Leftrightarrow$ Mô hình 1:

---

Mô hình được biểu diễn như sau:
tension_strength $=\overline{\boldsymbol{\beta}_{0}}+\overline{\boldsymbol{\beta}_{1}}$.layer_height $+\overline{\boldsymbol{\beta}_{2}}$.wall_thickness $+\ldots+\overline{\boldsymbol{\beta}_{0}}$.material $+\boldsymbol{\varepsilon}$
Ta thực hiện ước lượng các hệ số $\beta_{i}$ và dùng hàm linear_model(_) để tạo bảng kết quả:

| Call: |  |  |  |  |
| :--: | :--: | :--: | :--: | :--: |
| Im(formula = tension_streng | et = layer_height | $+$ wall_ |  |  |
|  | infill_density + infill_pattern | $+$ nozzle_temper |  |  |
|  | print_speed + material, data = new_D |  |  |  |
| Residuals: |  |  |  |  |
|  | Min 10 | Median | 30 | Max |
| $-9.4101-3.8491$ |  | 0.0338 | 3.9073 | 13.5086 |
| Coefficients: |  |  |  |  |
|  |  | Estimate | Std. Error | $t$ value $\operatorname{Pr}(>|t|)$ |
| (Intercept) |  | 171.62809 | 54.21779 | 3.166 | 0.00292 ** |
| layer_height |  | 55.59721 | 12.78771 | 4.348 | 8.87e-05 *** |
| wall_thickness |  | 1.06871 | 0.31942 | 3.346 | 0.00176 ** |
| infill_density |  | 0.16286 | 0.03415 | 4.769 | 2.35e-05 *** |
| infill_patternhoneycom |  | $-1.14271$ | 1.64581 | $-0.694$ | 0.49140 |
| nozzle_temper |  | $-1.04681$ | 0.36901 | $-2.837$ | 0.00705 ** |
| bed_temper |  | 1.00534 | 0.47426 | 2.120 | 0.04012 * |
| print_speed |  | $-0.01559$ | 0.03006 | $-0.519$ | 0.60679 |
| materialpl |  | $-17.30508$ | 8.51530 | $-2.032$ | 0.04864 * |
| Signif. codes: |  | 0 '***' | 0.001 '**' | 0.01 '*' | 0.05 '.' 0.1 ' ' 1 |
| Residual standard error: |  | 5.58 on 41 | degrees of freedom |  |  |
| Multiple R-squared: |  | 0.673, | Adjusted R-squared: |  | 0.6092 |
| F-statistic: |  | 10.55 on 8 and 41 DF, | p-value: 6.91e-08 |  |  |

Hình 17. Bảng kết quả ước lượng các hệ số $\beta_{i}$.
Residuals: sai số hồi quy (thặng dư hay phần dư) là độ chênh lệch giữa giá trị Y thực nghiệm và giá trị Y dự báo. Nhìn vào sai số hồi quy ta thấy được:

- $\mathrm{Q}_{1}$ : Giá trị của đường phân vị 1 là -3.8491 .
- $\mathrm{Q}_{2}$ : Giá trị của đường trung vị là 0.0338 .
- $\mathrm{Q}_{3}$ : Giá trị của đường phân vị 3 là 3.9073 .
- Max: Giá trị lớn nhất là 13.5086 .
- Min: Giá trị nhỏ nhất là -9.4101 .
* Coefficients: Hệ số.

Dựa vào kết quả của biến layer_height ta được:

- Estimate: Giá trị hệ số ước lượng là 55.59721 .
- Std. Error: Giá trị của sai số chuẩn hồi quy là 12.78771 .
- t-value: Giá trị của thống kê kiểm định là 4.348 .
- $\operatorname{Pr}(>|t|)$ : Giá trị kiểm định các hệ số hồi quy p-value là $8.87 .10^{-5}$.
* Signif code: Kí hiệu
* \# : Giá trị p - value từ $0 \rightarrow 0.001$

---

*     * Giá trị p - value từ $0.001 \rightarrow 0.01$
*: Giá trị p - value từ $0.01 \rightarrow 0.05$
-: Giá trị p - value từ $0.05 \rightarrow 0.1$
'': Giá trị p - value từ $0.1 \rightarrow 1$
* Residual standard error: Sai số chuẩn của sai số (s) là 5.58 với $s=\sqrt{\frac{S S E}{n-k-1}}$.Từ đây ta có thể tìm được SSE - Error Sum of Squares (tổng bình phương sai số), $S S E=$ $(n-k-1) \cdot s^{2}$ với $n-k-1=41$ trong đó n : số quan sát (cỡ mẫu), k : số biến độc lập có trong mô hình hồi quy đa biến.
* Multiple $\mathbf{R}$ - squared: Hệ số xác định $R^{2}$ là 0.673
* Adjusted R - squared: Hệ số xác định $R^{2}$ hiệu chính là 0.6092

Multiple R - squared và Adjusted R - squared dùng để đánh giá mức độ phù hợp của mô hình, R2 càng cao dẫn đến mô hình càng thích hợp đồng thời giải thích sự biến của biến phụ thuộc vào biến độc lập

Ta nhận thấy hệ số $\mathrm{R}^{2}$ hiệu chính (Adjusted R-Squared) là 0.6092 . Điều này thể hiện trong $100 \%$ sự thay đổi của sức căng bề mặt thì có $60.92 \%$ nguyên nhân gây ra sự thay đó đổi là do các biến độc lập có trong mô hình.

* F - statistic: giá trị thống kê kiểm định là 10.55 với $\mathrm{K}=8$ và $\mathrm{n}-\mathrm{k}-1=41$
* $\mathbf{p}$ - value: giá trị thống kê kiểm định là $6.91 .10^{-8}<\alpha=0.05$

F - statistic và p - value dùng để kiểm định các hệ số hồi quy có đồng thời bằng 0 hay khác 0 .

Phương trình hồi quy ước lượng:

# tension_strength $=\mathbf{1 7 1 . 6 2 8 0 9 + 5 5 . 5 9 7 2 1}$.layer_height <br> $+\mathbf{1 . 0 6 8 7 1}$.wall_thickness $+\ldots-\mathbf{1 7 . 3 0 5 0 8}$ material 

p-value hay $\operatorname{Pr}(>|\mathbf{t}|)$ : dùng để kiểm định các hệ số hồi quy
Giá thuyết $H_{0}: \beta_{i}=0$ (hệ số hồi quy không có ý nghĩa thống kê).
Giá thuyết $H_{1}: \beta_{i} \neq 0$ (hệ số hồi quy có ý nghĩa thống kê).
P-value ứng với 2 biến infill_partern ( 0,49140 ), print_speed $(0,60679)$ lớn hơn mức ý nghĩa $5 \%$ nên ta chưa bác bỏ được $\mathrm{H}_{0}$. Vì vậy hệ số hồi quy ứng với các biến này bằng 0 , hay nói các biến này không ảnh hưởng đến sức căng bề mặt của bản in. Do đó, ta sẽ loại bỏ 2 biến này ra khỏi mô hình.

## * Mô hình 2:

Xây dựng mô hình 2 là mô hình bỏ đi 2 biến infill_partern và print_speed.
Ta dùng hàm summary(mô hình 2) để tạo bảng tóm tắt kết quả:

---

![[753a4045d3240c9a8f090ccddefd8081_p27_img23.jpeg]]

Hình 18. Bảng kết quả mô hình ước lượng khi bỏ đi 2 biến infill_pattern và print_speed.
Như vậy phương trình ước lượng thể hiện mối quan hệ giữa các các biến và tension_strenght có dạng:

```
tension_strength = 167.02463 + 56.36695.layer_height +
1,11169wall_thickness ... - 17.10365materialpla.
```

Nhận xét: Mô hình 2 có $\mathrm{R}^{2}$ hiệu chỉnh bằng 0.6201 cao hơn so với $\mathrm{R}^{2}$ hiệu chỉnh ở mô hình 1 bằng 0.6092 nên có thể cho rằng mô hình 2 là mô hình hiệu quả hơn.

Ta sử dụng hệ số xác định $\mathrm{R}^{2}$ hiệu chỉnh để xét mô hình phù hợp mà không sử dụng hệ số xác định $\mathrm{R}^{2}$ vì khi ta đưa càng nhiều biến độc lập vào trong mô hình thì $\mathrm{R}^{2}$ càng tăng lên, càng thể hiện mô hình hồi quy rất tốt, tuy nhiên trong thực tế nếu đưa những biến không ảnh hưởng tới mô hình thì giá trị $R^{2}$ có sai số, $R^{2}$ hiệu chỉnh tính toán dựa trên những biến có ý nghĩa liên quan đến mô hình và giá trị $R^{2}$ hiệu chỉnh $\leq$ giá trị $R^{2}$ và đồng thời giảm mức độ phóng đại hiệu quả của mô hình và cân bằng lại hiệu quả mô hình.

# Tác động của các biến đối với tension_strength: 

Dựa vào p-value: Ta nhận thấy pvalue càng bé thì thể hiện biến đó càng tác động mạnh đến tension_strength. Từ đó cho thấy, layer_height và infill_density tác động mạnh nhất đối với tension_strenght, sau đó đến wall_thickness, nozzle_temperature, bed_temperature, materialpla.

Dựa vào hệ số hồi quy ước lượng: $\overline{B_{1}}=56.36695$ : Cho thấy khi ta tăng chiều cao mỗi lớp in lên 1 đơn vị, ta sẽ kỳ vọng giá trị sức căng bề mặt sẽ tăng 56.36695 x 1

---

$=56.36695$ đơn vị của sức căng bề mặt về mặt trung bình (trong trường hợp các biến khác không thay đổi) và tương tự với các biến còn lại.

# Các giả định trong mô hình hồi quy: 

- Y và các biến độc lập X có quan quan hệ tuyến tính.
- Sai số có phân phối chuẩn với kỳ vọng bằng 0 , phương sai của các sai số là hằng số.
- Các sai số $\epsilon_{1}, \ldots, \epsilon_{n}$ độc lập với nhau.


## 5.2. Thực hiện vẽ đồ thị kiểm tra các giả định:

Ta dùng hàm plot(mô hình 2) để vẽ các đồ thị Residuals and Fitted, Normall Q-Q, Scale - Location, Residuals and Leverage.

Đồ thị 1: Vẽ các sai số hồi quy tương ứng với giá trị dự báo, dùng để kiểm tra giả định:
![[753a4045d3240c9a8f090ccddefd8081_p28_img24.jpeg]]

Hình 19. Đồ thị Residuals and Fitted.

## Nhận xét:

Residuals and Fitted vẽ các giá trị thặng dư (sai số) tương ứng với các giá trị dự báo.
Đường màu đỏ chưa thực sự là đường thẳng nằm ngang nên giả định Y và các biến độc lập X có quan hệ tuyến tính chưa hẳn thoả mãn.

Đường màu đỏ chưa nằm sát đường đứt nét residual bằng 0 (đường $y=0$ ) nên giả định sai số có kỳ vọng bằng 0 chưa thoả mãn.

Các giá trị sai số chưa phân tán ngẫu nhiên dọc theo đường màu đỏ, nên giả định phương sai các sai số là hằng số chưa thực sự thoả mãn.

Đồ thị 2: Vẽ các sai số hồi quy được chuẩn hoá, dùng để kiểm tra giả định sai số có phân phối chuẩn.

---

![[753a4045d3240c9a8f090ccddefd8081_p29_img25.jpeg]]

Hình 20. Đồ thị Normall Q-Q.
Normall Q-Q vẽ các giá trị thặng dư được chuẩn hoá. Ta nhận thấy các giá trị này nắm dọc theo đường dứt nét kỳ vọng phân phối chuẩn nên giả định sai số có phân phối chuẩn tương đối thoả mãn.

* Đồ thị 3: Vẽ căn bậc 2 các sai số được chuẩn hoá, dùng để kiểm tra giả định phương sai các sai số là hằng số.
![[753a4045d3240c9a8f090ccddefd8081_p29_img26.jpeg]]

Hình 21. Đồ thị Scale - Location.
Scale - Location vẽ căn bậc hai các giá trị thặng du được chuẩn hoá. Ta nhận thấy đường màu đỏ không phải là đường thẳng nằm ngang và các giá trị này không phân tán dọc theo đường màu đỏ nên giả định sai số có phương sai là hằng số chưa thực sự thoả mãn.

* Đồ thị 4: Vẽ các điểm có thể gây ảnh hưởng cao trong bộ dữ liệu.

---

![[753a4045d3240c9a8f090ccddefd8081_p30_img27.jpeg]]

Hình 22. Đồ thị Residuals and Leverage.
Residuals and Leverage vẽ các điểm có thể gây ảnh hưởng cao trong bộ dữ liệu. Ta nhận thấy các điểm 3,11 và 40 là những điểm có thể gây ảnh hưởng cao trong bộ dữ liệu, tuy nhiên các điểm này chưa vượt ra khỏi đường gạch đứt Cook's Distances. Vì vậy, ta chưa cần phải loại bỏ những điểm này ra khỏi bộ dữ liệu.

---

# PHÂN 6. THĀO LUẬN VÀ MỞ RỘNG 

Ưu điểm của phương pháp hồi quy chính là một phương pháp thống kê để thiết lập mối quan hệ giữa một biến phụ thuộc và một nhóm tập hợp các biến độc lập. Mô hình với một biến phụ thuộc với hai hoặc nhiều biến độc lập được gọi là hồi quy bội (hay còn gọi là hồi quy đa biến).

Hồi quy tuyến tính bội dễ hiểu và dễ triển khai, đặc biệt khi các biến có mối quan hệ tuyến tính và hiệu quả tính toán của phương pháp này có thể được tính toán nhanh chóng ngay cả với dữ liệu lớn, nhờ các thuật toán tối ưu hóa hiệu quả.

Dự đoán chính xác các biến độc lập có mối quan hệ tuyến tính mạnh với biến phụ thuộc, phương pháp hồi quy tuyến tính bội có thể cung cấp các dự đoán chính xác, các hệ số hồi quy tuyến tính bội cung cấp thông tin về mối quan hệ giữa từng biến độc lập và biến phụ thuộc, giúp hiểu rõ hơn về ảnh hưởng của từng yếu tố. và tiện lợi cho kiểm định giả thuyết, dễ dàng thực hiện các kiểm định giả thuyết về các hệ số hồi quy để kiểm tra sự ảnh hưởng của các biến độc lập.

Tuy nhiên mô hình cũng có một số nhược điểm như: Phương pháp này giả định rằng mối quan hệ giữa các biến độc lập và biến phụ thuộc là tuyến tính, điều này không phải lúc nào cũng đúng trong thực tế, hồi quy tuyến tính bội rất nhạy cảm với các điểm dữ liệu ngoại lệ, có thể làm sai lệch mô hình.

Khi các biến độc lập có tương quan cao với nhau, nó có thể gây ra đa cộng tuyến, làm cho các ước lượng hệ số hồi quy không ổn định và khó diễn giải. Phương pháp này giả định rằng các sai số có phân phối chuẩn và có phương sai không đổi. Nếu các giả định này không được thỏa mãn, kết quả hồi quy có thể không tin cậy.

Không phù hợp cho các mối quan hệ phi tuyến tính: Đối với các mối quan hệ phi tuyến tính giữa các biến, hồi quy tuyến tính bội không phải là lựa chọn tốt nhất. Các phương pháp khác như hồi quy phi tuyến hoặc mô hình cây quyết định có thể phù hợp hơn.

Ngoài ra, đề tài ta có thể phân tích xây dựng bổ sung hai mô hình hồi quy của hai biến roughness và elongation dựa trên cách thức giống như xây dựng mô hình ứng với biến tension_strenght. Từ những phương pháp này mà đề tài đã đánh giá được hiệu quả những yếu tố của biến ảnh hưởng đến các sức căng bề in 3D theo như bài toán đã được đặt ra.

## PHÂN 7. NGUÔN DỮ LIỆU VÀ NGUÔN CODE

Dữ liệu: Data
Nguồn Code: Data Code

---

# PHÂN 8. TÀI LIỆU THAM KHẢO 

[1] Nguyễn Đình Huy, Đậu Thế Cấp và Lưu Xuân Đại (2019), Giáo trình Xác suất Thống kê, Nxb. ĐHQG Tp Hồ Chí Minh, Tp Hồ Chí Minh.
[2] Peter Dalgaard, Introductory Statistic with R, Springer 2008.
[3] Nguyễn Tiến Dũng, Đỗ Đức Thái, Nhập môn hiện đại Xác suất \& Thống kê, 2015
[5] Nguyễn Văn Tuấn, Xử lí số liệu và biểu đồ bằng R.

---

# PHÂN 9. CÁC LỆNH CODE 

### 9.1. Tiền xử lý sổ liệu.

Đọc dữ liệu.

| threedprint_data <- read.csv("C:/Users/DELL/Desktop/RStudio/data.csv") <br> head(threedprint_data,10) <br> ## layer_height wall_thickness infill_density infill_pattern nozzle_temp <br> erature |  |  |  |  |  |
| :--: | :--: | :--: | :--: | :--: | :--: |
| \#\# 1 <br> 220 | 0.02 | 8 | 90 | grid |  |
| \#\# 2 <br> 225 | 0.02 | 7 | 90 | honeycomb |  |
| \#\# 3 <br> 230 | 0.02 | 1 | 80 | grid |  |
| \#\# 4 <br> 240 | 0.02 | 4 | 70 | honeycomb |  |
| \#\# 5 <br> 250 | 0.02 | 6 | 90 | grid |  |
| \#\# 6 <br> 200 | 0.02 | 10 | 40 | honeycomb |  |
| \#\# 7 <br> 205 | 0.02 | 5 | 10 | grid |  |
| \#\# 8 <br> 210 | 0.02 | 10 | 10 | honeycomb |  |
| \#\# 9 <br> 215 | 0.02 | 9 | 70 | grid |  |
| \#\# 10 <br> 220 | 0.02 | 8 | 40 | honeycomb |  |
| \#\# bed_temperature print_speed material fan_speed roughness tension_stre <br> ngth |  |  |  |  |  |
| \#\# 1 <br> 18 | 60 | 40 | abs | 0 | 25 |
| \#\# 2 <br> 16 | 65 | 40 | abs | 25 | 32 |
| \#\# 3 <br> 8 | 70 | 40 | abs | 50 | 40 |
| \#\# 4 <br> 10 | 75 | 40 | abs | 75 | 68 |
| \#\# 5 <br> 5 | 80 | 40 | abs | 100 | 92 |
| \#\# 6 <br> 24 | 60 | 40 | pla | 0 | 60 |

---

| $\begin{array}{ll} \text { \#\# } 7 \\ 12 \end{array}$ | 65 | 40 | pla | 25 | 55 |
| :--: | :--: | :--: | :--: | :--: | :--: |
| \#\# 8 <br> 14 | 70 | 40 | pla | 50 | 21 |
| \#\# 9 <br> 27 | 75 | 40 | pla | 75 | 24 |
| \#\# 10 <br> 25 | 80 | 40 | pla | 100 | 30 |
| \#\# elongation |  |  |  |  |  |
| \#\# 1 | 1.2 |  |  |  |  |
| \#\# 2 | 1.4 |  |  |  |  |
| \#\# 3 | 0.8 |  |  |  |  |
| \#\# 4 | 0.5 |  |  |  |  |
| \#\# 5 | 0.7 |  |  |  |  |
| \#\# 6 | 1.1 |  |  |  |  |
| \#\# 7 | 1.3 |  |  |  |  |
| \#\# 8 | 1.5 |  |  |  |  |
| \#\# 9 | 1.4 |  |  |  |  |
| \#\# 10 | 1.7 |  |  |  |  |

```
new_DF <- threedprint_data[,c("layer_height","wall_thickness","infill_densi
ty",
"infill_pattern","nozzle_temperature","bed_temperature","print_speed",
"material","fan_speed","tension_strength")]
head(new_DF,15)
## layer_height wall_thickness infill_density infill_pattern nozzle_temp
erature
## 1
220
## 2
225
## 3
230
## 4
240
## 5
250
```

---

| \#\# 6 <br> 200 | 0.02 | 10 | 40 | honeycomb |
| :--: | :--: | :--: | :--: | :--: |
| \#\# 7 <br> 205 | 0.02 | 5 | 10 | grid |
| \#\# 8 <br> 210 | 0.02 | 10 | 10 | honeycomb |
| \#\# 9 <br> 215 | 0.02 | 9 | 70 | grid |
| \#\# 10 <br> 220 | 0.02 | 8 | 40 | honeycomb |
| \#\# 11 <br> 220 | 0.06 | 6 | 80 | grid |
| \#\# 12 <br> 225 | 0.06 | 2 | 20 | honeycomb |
| \#\# 13 <br> 230 | 0.06 | 10 | 50 | grid |
| \#\# 14 <br> 240 | 0.06 | 6 | 10 | honeycomb |
| \#\# 15 <br> 250 | 0.06 | 3 | 50 | grid |
| \#\# bed_temperature print_speed material fan_speed tension_strength |  |  |  |  |
| \#\# 1 | 60 | 40 | abs | 018 |
| \#\# 2 | 65 | 40 | abs | 2516 |
| \#\# 3 | 70 | 40 | abs | 508 |
| \#\# 4 | 75 | 40 | abs | 7510 |
| \#\# 5 | 80 | 40 | abs | 1005 |
| \#\# 6 | 60 | 40 | pla | 024 |
| \#\# 7 | 65 | 40 | pla | 2512 |
| \#\# 8 | 70 | 40 | pla | 5014 |
| \#\# 9 | 75 | 40 | pla | 7527 |
| \#\# 10 | 80 | 40 | pla | 10025 |
| \#\# 11 | 60 | 60 | abs | 037 |
| \#\# 12 | 65 | 60 | abs | 2512 |
| \#\# 13 | 70 | 60 | abs | 5016 |
| \#\# 14 | 75 | 60 | abs | 759 |
| \#\# 15 | 80 | 60 | abs | 10010 |
| colSums(is.na(new_DF)) |  |  |  |  |
| \#\# layer_height wall_thickness infill_density infill_patt |  |  |  |  |

---

| \#\# 0 | 0 | 0 | 0 |
| :--: | :--: | :--: | :--: |
| \#\# nozzle_temperature | bed_temperature | print_speed | mater |
|  |  |  |  |
| \#\# 0 | 0 | 0 | 0 |
| \#\# fan_speed | tension_strength |  |  |
| \#\# | 0 | 0 |  |

# 9.2. Thống kê tã. 

```
new_function <- function(x){
    c(n=length(x),xtb=mean(x),sd=sd(x),Q1=quantile(x,probs=0.25),
    Q2 = median(x),Q3=quantile(x,probs=0.75),min=min(x),max=max(x))}
```

continous_data <- new_DF[,c("layer_height","wall_thickness","infill_density ",
"nozzle_temperature","bed_temperature","print_speed",
"fan_speed","tension_strength")]
apply(continous_data,2,new_function)
\#\# layer_height wall_thickness infill_density nozzle_temperature
\#\# n 50.00000000 50.000000 50.00000 50.00000
\#\# xtb 0.10600000 5.220000 53.40000 221.50000
\#\# sd 0.06439673 2.922747 25.36348 14.82035
\#\# Q1.25\% 0.06000000 3.000000 40.00000 210.00000
\#\# Q2 0.10000000 5.000000 50.00000 220.00000
\#\# Q3.75\% 0.15000000 7.000000 80.00000 230.00000
\#\# min 0.02000000 1.000000 10.00000 200.00000
\#\# max 0.20000000 10.000000 90.00000 250.00000
\#\# bed_temperature print_speed fan_speed tension_strength
\#\# n 50.000000 50.0000 50.00000 50.000000
\#\# xtb 70.000000 64.0000 50.00000 20.080000
\#\# sd 7.142857 29.6923 35.71429 8.925634
\#\# Q1.25\% 65.000000 40.0000 25.00000 12.000000
\#\# Q2 70.000000 60.0000 50.00000 19.000000
\#\# Q3.75\% 75.000000 60.0000 75.00000 27.000000
\#\# min 60.000000 40.0000 0.00000 4.000000

---

```
## max 80.000000 120.0000 100.00000 37.000000
table(new_DF$infill_pattern)
##
## grid honeycomb
## 25 25
table(new_DF$material)
##
## abs pla
## 25 25
hist(new_DF$tension_strength,xlab="tension_strength",
main="Histogram of tension_strength",col="pink",labels=T,ylim=c(0,15))
boxplot(tension_strength~infill_pattern,new_DF,col=c("red","blue"),
main="tension_strength and infill_pattern")
boxplot(tension_strength~material,new_DF,col=c("red","blue"),
main="tension_strength and material")
plot(new_DF$layer_height,new_DF$tension_strength,xlab="layer_height",
ylab="tension_strength",main="layer_height & tension_strength")
plot(new_DF$wall_thickness,new_DF$tension_strength,xlab="wall_thickness",
ylab="tension_strength",main="wall_thickness & tension_strength")
plot(new_DF$infill_density,new_DF$tension_strength,xlab="infill_density",
ylab="tension_strength",main="infill_density & tension_strength")
plot(new_DF$nozzle_temperature,new_DF$tension_strength,xlab="nozzle_tempera
ture",
ylab="tension_strength",main="nozzle_temperature & tension_strength")
```

---

```
plot(new_DF$bed_temperature,new_DF$tension_strength,xlab="bed_temperature",
ylab="tension_strength",main="bed_temperature & tension_strength")
```

```
plot(new_DF$print_speed,new_DF$tension_strength,xlab="print_speed",
ylab="tension_strength",main="print_speed & tension_strength")
```

```
plot(new_DF$fan_speed,new_DF$tension_strength,xlab="fan_speed",
ylab="tension_strength",main="fan_speed & tension_strength")
```


# library (corrplot) 

\#\# corrplot 0.92 loaded
corrplot(cor(continous_data), method = "number")

## 9.3. Thống kê suy diễn.

```
            model_1 <- lm(tension_strength~layer_height+wall_thickness+infill_d
ensity+infill_pattern+nozzle_temperature+bed_temperature+print_speed+materi
al, data=new_DF)
    summary(model_1)
##
## Call:
## lm(formula = tension_strength ~ layer_height + wall_thickness +
## infill_density + infill_pattern + nozzle_temperature + bed_temperatu
re +
## print_speed + material, data = new_DF)
##
## Residuals:
## Min 1Q Median 3Q Max
## -9.4101 -3.8491 0.0338 3.9073 13.5086
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) 171.62809 54.21779 3.166 0.00292 **

---

| \#\# layer_height | 55.59721 | 12.78771 | 4.348 | $8.87 \mathrm{e}-05$ | $* * *$ |
| :--: | :--: | :--: | :--: | :--: | :--: |
| \#\# wall_thickness | 1.06871 | 0.31942 | 3.346 | 0.00176 | ** |
| \#\# infill_density | 0.16286 | 0.03415 | 4.769 | $2.35 \mathrm{e}-05$ | *** |
| \#\# infill_patternhoneycomb | $-1.14271$ | 1.64581 | $-0.694$ | 0.49140 |  |
| \#\# nozzle_temperature | $-1.04681$ | 0.36901 | $-2.837$ | 0.00705 | ** |
| \#\# bed_temperature | 1.00534 | 0.47426 | 2.120 | 0.04012 | * |
| \#\# print_speed | $-0.01559$ | 0.03006 | $-0.519$ | 0.60679 |  |
| \#\# materialpla | $-17.30508$ | 8.51530 | $-2.032$ | 0.04864 | * |
| \#\# --- |  |  |  |  |  |
| \#\# Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 |  |  |  |  |  |
| \#\# |  |  |  |  |  |
| \#\# Residual standard error: 5.58 on 41 degrees of freedom |  |  |  |  |  |
| \#\# Multiple R-squared: 0.673, Adjusted R-squared: 0.6092 |  |  |  |  |  |
| \#\# F-statistic: 10.55 on 8 and 41 DF, p-value: 6.91e-08 |  |  |  |  |  |

# MÕ HÌNH 2: 

```
    model_2 <- lm(tension_strength-layer_height+wall_thickness+infill_density
+nozzle_temperature+bed_temperature+material,data=new_DF)
    summary(model_2)
##
## Call:
## lm(formula = tension_strength ~ layer_height + wall_thickness +
## infill_density + nozzle_temperature + bed_temperature + material,
## data = new_DF)
##
## Residuals:
## Min 1Q Median 3Q Max
## -9.4717 -4.1695 0.0914 3.8586 13.9581
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) 167.02463 53.19880 3.140 0.003055 **
## layer_height 56.36695 12.44845 4.528 4.67e-05 ***
## wall_thickness 1.11169 0.28024 3.967 0.000271 ***
## infill_density 0.16643 0.03339 4.985 1.06e-05 ***
```

---

```
## nozzle_temperature -1.02890 0.36321 -2.833 0.006996 **
## bed_temperature 0.98346 0.46685 2.107 0.041026 *
## materialpla -17.10365 8.39202 -2.038 0.047722 *
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
##
## Residual standard error: 5.501 on 43 degrees of freedom
## Multiple R-squared: 0.6667, Adjusted R-squared: 0.6201
## F-statistic: 14.33 on 6 and 43 DF, p-value: 6.783e-09
    lm(formula = tension_strength ~ layer_height + wall_thickness + infil
l_density + nozzle_temperature + bed_temperature + material, data = new_DF)
##
## Call:
## lm(formula = tension_strength ~ layer_height + wall_thickness +
## infill_density + nozzle_temperature + bed_temperature + material,
## data = new_DF)
##
## Coefficients:
## (Intercept) layer_height wall_thickness infill_d
ensity
## 167.0246 56.3670 1.1117
0.1664
## nozzle_temperature bed_temperature materialpla
## -1.0289 0.9835 -17.1036
par(mfrow=c(2,2))
plot(model_2)
```

```
hist(threedprint_data$roughness,xlab="roughness",main= "Histogram of roug
hness",col="pink", labels =T, ylim = c(0,15))
    hist(threedprint_data$elongation,xlab="elongation",main= "Histogram of
elongation",col="green", labels =T, ylim = c(0,15))
    boxplot(threedprint_data$roughness~threedprint_data$infill_pattern,xlab
="infill_pattern", ylab="rouughness", col="yellow")
    boxplot(threedprint_data$roughness~threedprint_data$material,xlab="materi
al",ylab="rouughness", col="gray")
```

---

```
    boxplot(threedprint_data$tension_strength-threedprint_data$infill_pattern
,xlab="infill_pattern",ylab="tension_strength",col="blue")
    boxplot(threedprint_data$tension_strength-threedprint_data$material,xlab=
"material",ylab="tension_strength",col="navy")
    boxplot(threedprint_data$elongation-threedprint_data$infill_pattern,xlab=
"infill_pattern",ylab="elongation",col="purple")
    boxplot(threedprint_data$elongation-threedprint_data$material,xlab="mater
ial",ylab="elongation",col="purple")
```

```
plot(threedprint_data$elongation,threedprint_data$layer_height,xlab="elon
gation",ylab="layer_height",main = "elongation and layer_height")
plot(threedprint_data$elongation,threedprint_data$wall_thickness,xlab="el
ongation",ylab="wall_thickness",main = "elongation and wall_thickness")
plot(threedprint_data$elongation,threedprint_data$infill_density,xlab="el
ongation",ylab="infill_density",main = "elongation and infill_density")
plot(threedprint_data$elongation,threedprint_data$nozzle_temperature,xlab
="elongation",ylab="nozzle_temperature",main = "elongation and nozzle_tempe
rature")
```

plot(threedprint_data\$elongation,threedprint_data\$bed_temperature,xlab="e
longation",ylab="bed_temperature",main = "elongation and bed_temperature")
plot(threedprint_data\$elongation,threedprint_data\$fan_speed,xlab="elongat
ion",ylab="fan_speed",main = "elongation and fan_speed")
plot(threedprint_data\$elongation,threedprint_data\$print_speed,xlab="elong ation",ylab="print_speed",main = "elongation and print_speed")
plot(threedprint_data\$roughness,threedprint_data\$print_speed,xlab="roughn ess",ylab="print_speed",main = "roughness and print_speed")
plot(threedprint_data\$roughness,threedprint_data\$fan_speed,xlab="roughnes s",ylab="fan_speed",main = "roughness and fan_speed")
plot(threedprint_data\$roughness,threedprint_data\$nozzle_temperature,xlab= "roughness",ylab="nozzle_temperature",main = "roughness and nozzle_temperat ure")
plot(threedprint_data\$roughness,threedprint_data\$bed_temperature,xlab="ro ughness",ylab="bed_temperature",main = "roughness and bed_temperature")
plot(threedprint_data\$roughness,threedprint_data\$infill_density,xlab="rou ghness",ylab="infill_density",main = "roughness and infill_density")

---

```
    plot(threedprint_data$roughness,threedprint_data$wall_thickness,xlab="rou
ghness",ylab="wall_thickness",main = "roughness and wall_thickness")
    plot(threedprint_data$roughness,threedprint_data$layer_height,xlab="rough
ness",ylab="layer_height",main = "roughness and layer_height")
```


# MÕ HÌNH 3 

```
model_3 <- lm(roughness~layer_height+wall_thickness+infill_density+infill_p
    attern+nozzle_temperature+bed_temperature+print_speed+material,data=threedp
    rint_data)
    summary(model_3)
##
## Call:
## lm(formula = roughness ~ layer_height + wall_thickness + infill_density
*
## infill_pattern + nozzle_temperature + bed_temperature + print_speed
*
## material, data = threedprint_data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -72.746 -24.332 -1.641 20.304 96.552
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) -2.371e+03 3.716e+02 -6.379 1.25e-07 ***
## layer_height 1.269e+03 8.765e+01 14.483 < 2e-16 ***
## wall_thickness 2.334e+00 2.189e+00 1.066 0.29259
## infill_density -4.231e-02 2.341e-01 -0.181 0.85742
## infill_patternhoneycomb -1.255e-01 1.128e+01 -0.011 0.99117
## nozzle_temperature 1.506e+01 2.529e+00 5.953 5.05e-07 ***
## bed_temperature -1.613e+01 3.251e+00 -4.962 1.27e-05 ***
## print_speed 6.496e-01 2.060e-01 3.153 0.00302 **
## materialpla 2.985e+02 5.836e+01 5.114 7.78e-06 ***
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
##
## Residual standard error: 38.24 on 41 degrees of freedom
```

---

```
## Multiple R-squared: 0.8752, Adjusted R-squared: 0.8509
## F-statistic: 35.95 on 8 and 41 DF, p-value: 3.834e-16
    lm(formula = roughness ~ layer_height + wall_thickness + infill_density +
        infill_pattern + nozzle_temperature + bed_temperature + print_spee
d +
        material, data = threedprint_data)
##
## Call:
## lm(formula = roughness ~ layer_height + wall_thickness + infill_density
+
## infill_pattern + nozzle_temperature + bed_temperature + print_speed
+
## material, data = threedprint_data)
##
## Coefficients:
## (Intercept) layer_height wall_thicknes
s
## -2.371e+03 1.269e+03 2.334e+0
0
## infill_density infill_patternhoneycomb nozzle_temperatur
e
## -4.231e-02 -1.255e-01 1.506e+0
1
## bed_temperature print_speed materialpl
a
## -1.613e+01 6.496e-01 2.985e+0
2
```


# MÕ HÌNH 4 

```
    model_4 <- lm(roughness~layer_height+nozzle_temperature+bed_temperature+p
rint_speed+material,data=threedprint_data)
    summary(model_4)
##
## Call:
## lm(formula = roughness ~ layer_height + nozzle_temperature +
## bed_temperature + print_speed + material, data = threedprint_data)
##
## Residuals:
## Min 1Q Median 3Q Max
```

---

```
## -74.084 -26.500 -1.662 22.585 92.356
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) -2310.7356 353.2009 -6.542 5.38e-08 ***
## layer_height 1246.5353 83.1780 14.986 < 2e-16 ***
## nozzle_temperature 14.7774 2.3979 6.163 1.95e-07 ***
## bed_temperature -15.8078 3.0895 -5.117 6.55e-06 ***
## print_speed 0.5538 0.1804 3.070 0.00366 **
## materialpla 294.1610 56.1586 5.238 4.38e-06 ***
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
##
## Residual standard error: 37.44 on 44 degrees of freedom
## Multiple R-squared: 0.8717, Adjusted R-squared: 0.8571
## F-statistic: 59.78 on 5 and 44 DF, p-value: < 2.2e-16
lm(formula = roughness ~ layer_height + nozzle_temperature +
    bed_temperature + print_speed + material, data = threedprint_data)
##
## Call:
## lm(formula = roughness ~ layer_height + nozzle_temperature +
## bed_temperature + print_speed + material, data = threedprint_data)
##
## Coefficients:
## (Intercept) layer_height nozzle_temperature bed_tempe
```

rature
\#\# -2310.7356 1246.5353 14.7774 -1
5.8078
\#\# print_speed materialpla
\#\# 0.5538 294.1610

MÕ HÌNH 5

```
model_5 <- lm(elongation~layer_height+wall_thickness+infill_density+infill
    pattern+nozzle_temperature+bed_temperature+print_speed+material,data=three
dprint_data)
    summary(model_5)
##
```

---

```
## Call:
## lm(formula = elongation ~ layer_height + wall_thickness + infill_density
    4
## infill_pattern + nozzle_temperature + bed_temperature + print_speed
+
## material, data = threedprint_data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -0.99066 -0.37634 0.03137 0.26680 0.86971
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) 18.435640 4.466801 4.127 0.000175 ***
## layer_height 6.382037 1.053532 6.058 3.58e-07 ***
## wall_thickness 0.030827 0.026316 1.171 0.248194
## infill_density 0.009890 0.002813 3.516 0.001086 **
## infill_patternhoneycomb -0.062282 0.135592 -0.459 0.648422
## nozzle_temperature -0.109642 0.030401 -3.607 0.000834 ***
## bed_temperature 0.104223 0.039073 2.667 0.010894 *
## print_speed -0.003375 0.002477 -1.363 0.180405
## materialpla -1.783730 0.701544 -2.543 0.014876 *
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
##
## Residual standard error: 0.4597 on 41 degrees of freedom
## Multiple R-squared: 0.7154, Adjusted R-squared: 0.6598
## F-statistic: 12.88 on 8 and 41 DF, p-value: 4.765e-09
lm(formula = elongation ~ layer_height + wall_thickness + infill_dens
ity +
infill_pattern + nozzle_temperature + bed_temperature + print_sp
eed +
material, data = threedprint_data)
##
## Call:
## lm(formula = elongation ~ layer_height + wall_thickness + infill_density
+
```

---

```
## infill_pattern + nozzle_temperature + bed_temperature + print_speed
+
## material, data = threedprint_data)
##
## Coefficients:
## (Intercept) layer_height wall_thickness
5
## 18.435640 6.382037 0.03082
7
## infill_density infill_patternhoneycomb nozzle_temperatur
e
## 0.009890 -0.062282 -0.10964
2
## bed_temperature print_speed materialpl
a
## 0.104223 -0.003375 -1.78373
0
```


# MÕ HÌNH 6 

```
model_6 <- lm(elongation~layer_height+infill_density+nozzle_temperature+bed
_temperature+print_speed+material,data=threedprint_data)
    summary(model_6)
##
## Call:
## lm(formula = elongation ~ layer_height + infill_density + nozzle_tempera
ture +
## bed_temperature + print_speed + material, data = threedprint_data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -1.12952 -0.32192 0.05021 0.30777 0.83809
##
## Coefficients:
## Estimate Std. Error t value Pr(>|t|)
## (Intercept) 19.023103 4.384019 4.339 8.5le-05 ***
## layer_height 6.079479 1.014849 5.991 3.77e-07 ***
## infill_density 0.010456 0.002750 3.802 0.000448 ***
## nozzle_temperature -0.112096 0.030029 -3.733 0.000551 ***
## bed_temperature 0.106920 0.038632 2.768 0.008295 **

---

```
## print_speed -0.004639 0.002212 -2.097 0.041909 *
## materialpla -1.824195 0.695511 -2.623 0.012016 *
## ---
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
##
## Residual standard error: 0.4568 on 43 degrees of freedom
## Multiple R-squared: 0.7053, Adjusted R-squared: 0.6642
## F-statistic: 17.15 on 6 and 43 DF, p-value: 5.335e-10
lm(formula = elongation ~ layer_height + infill_density + nozzle_tem
perature +
    bed_temperature + print_speed + material, data = threedprint_da
ta)
##
## Call:
## lm(formula = elongation ~ layer_height + infill_density + nozzle_tempera
ture +
## bed_temperature + print_speed + material, data = threedprint_data)
##
## Coefficients:
## (Intercept) layer_height infill_density nozzle_tempe
rature
## 19.023103 6.079479 0.010456 -0.
112096
## bed_temperature print_speed materialpla
## 0.106920 -0.004639 -1.824195
par(mfrow=c(2,2))
plot(model_6)
```

------HÉT------